### ISSUE TITLE
erro ao criar o client (client.go:52)

### ISSUE THREAD

**Issue by deguree2718** [luizalabs/id-magalu-cli#4]
#3 
#2 
![image](https://github.com/luizalabs/id-magalu-cli/assets/85945180/d6e3560f-6822-42a4-a26f-23c5baab8fae)

mesmo problema das duas issues marcadas acima, também abri um chamado no ZenDesk há 4 dias já, e ainda não obtive resposta
estamos sendo cobrados a fazer a integração nova, e com esse problema simplesmente não tem possibilidade de fazer

**Comment by mgpeixoto** [comment]
@deguree2718 tudo bem?
O time fez um ajuste no README, tente criar o client novamente com o exemplo do README.

**Comment by ViniciusR22** [comment]
@mgpeixoto Bom dia, estamos com o mesmo problema, temos prazo para integrar com a magalu e não conseguimos devido ao erro, ja seguimos o readme e não resolve.
